### ISSUE TITLE
PIC32-PINGUINO-OTG A6 and A7 pins swapped

### ISSUE THREAD

**Issue by vicpino** [OLIMEX/Arduino_configurations#3]
On the PIC32-PINGUINO and PIC32-PINGUINO-OTG boards from Olimex the pin marked A6 on the silkscreen is connected to RB11 and the pin marked A7 is connected to RB10.
The file Board_Data.c on /Versions/1.2.1/variants/PIC32_Pinguino_OTG on lines 209 and 210 should be corrected.

**Comment by Stanimir-Petev** [comment]
Thank you for the report! This is now fixed in commit:
https://github.com/OLIMEX/Arduino_configurations/commit/cb55b90f108a7aa7be3efe579a03e28eb7f5df88
