### ISSUE TITLE
PIC32-PINGUINO-OTG pins D8 and D9 assignment mismatch

### ISSUE THREAD

**Issue by vicpino** [OLIMEX/Arduino_configurations#5]
On the PIC32-PINGUINO-OTG board from Olimex 
the pin marked D8 on the silkscreen is connected to RB13 
and the pin marked D9 is connected to RB14
(in this board RB15 is used to monitor the signal FAULT_B from the USB power IC).
The file Board_Data.c on /Versions/1.2.3/variants/PIC32_Pinguino_OTG 
on lines 182 and 183 should be corrected and maybe also the comments on lines 128 and 129.

**Comment by Stanimir-Petev** [comment]
Thanks for the correction! The fix has been commited and you can update it.
